using System.Text;

namespace SqlExplorer.Tools.CopyTable;

/// <summary>
/// Renders a <c>CREATE TABLE</c> for a <see cref="TableModel"/>, quoting identifiers for the engine the
/// copy targets (same provider as the source — the picker enforces that). Pure and unit-tested; the data
/// half of the copy is generated separately by the SDK's <c>InsertScripter</c>.
/// </summary>
public static class CreateTableWriter
{
    public static string QuoteId(string providerId, string id) => providerId switch
    {
        "mysql" => "`" + id.Replace("`", "``") + "`",
        "sqlserver" => "[" + id.Replace("]", "]]") + "]",
        _ => "\"" + id.Replace("\"", "\"\"") + "\""      // postgres / sqlite / generic
    };

    public static string QuoteTable(string providerId, TableModel t) =>
        string.IsNullOrEmpty(t.Schema)
            ? QuoteId(providerId, t.Name)
            : $"{QuoteId(providerId, t.Schema)}.{QuoteId(providerId, t.Name)}";

    /// <param name="keepIdentity">When true the copy preserves the source's identity values: identity columns
    /// become plain columns (their sequence/auto default dropped) so the original values insert cleanly on any
    /// engine. When false the target regenerates them: the column keeps the engine's identity clause and is
    /// left out of the insert (see <see cref="ColumnsForInsert"/>).</param>
    public static string Build(string providerId, TableModel table, bool keepIdentity)
    {
        var body = new List<string>();
        foreach (var c in table.Columns.OrderBy(c => c.Ordinal))
        {
            var spec = new StringBuilder();
            spec.Append(QuoteId(providerId, c.Name)).Append(' ').Append(c.DataType);

            if (c.IsIdentity && !keepIdentity)
            {
                spec.Append(IdentityClause(providerId));
            }

            if (!c.Nullable)
            {
                spec.Append(" NOT NULL");
            }

            // A serial/auto default (e.g. Postgres nextval(...)) points at a sequence that won't exist on the
            // target, so it's dropped for identity columns; a plain default is carried over verbatim.
            if (!string.IsNullOrWhiteSpace(c.Default) && !c.IsIdentity)
            {
                spec.Append(" DEFAULT ").Append(c.Default);
            }

            body.Add(spec.ToString());
        }

        if (table.PrimaryKey is { Columns.Count: > 0 } pk)
        {
            var cols = string.Join(", ", pk.Columns.Select(c => QuoteId(providerId, c)));
            body.Add(string.IsNullOrEmpty(pk.Name)
                ? $"PRIMARY KEY ({cols})"
                : $"CONSTRAINT {QuoteId(providerId, pk.Name)} PRIMARY KEY ({cols})");
        }

        var sb = new StringBuilder();
        sb.Append("CREATE TABLE ").Append(QuoteTable(providerId, table)).Append(" (\n    ");
        sb.Append(string.Join(",\n    ", body));
        sb.Append("\n);");
        return sb.ToString();
    }

    /// <summary>A <c>DROP TABLE IF EXISTS</c> for the target, guarding a re-copy. SQL Server got
    /// <c>DROP TABLE IF EXISTS</c> in 2016; the others have had it for years.</summary>
    public static string DropIfExists(string providerId, TableModel table) =>
        $"DROP TABLE IF EXISTS {QuoteTable(providerId, table)};";

    /// <summary>The columns actually written by the insert: all of them when <paramref name="keepIdentity"/>,
    /// or every non-identity column when the target regenerates the identity. Drives the source <c>SELECT</c>
    /// so the read and the insert line up.</summary>
    public static IReadOnlyList<TableColumn> ColumnsForInsert(TableModel table, bool keepIdentity) =>
        keepIdentity ? table.Columns : table.Columns.Where(c => !c.IsIdentity).ToList();

    private static string IdentityClause(string providerId) => providerId switch
    {
        "sqlserver" => " IDENTITY(1,1)",
        "mysql" => " AUTO_INCREMENT",
        _ => " GENERATED BY DEFAULT AS IDENTITY"        // postgres / generic
    };
}
