using SqlExplorer.Tools.CopyTable;

namespace SqlExplorer.Tools.CopyTable.Tests;

public class CreateTableWriterTests
{
    private static TableModel Table(string schema, string name, IReadOnlyList<TableColumn> cols, TablePrimaryKey? pk = null) =>
        new(schema, name, cols, pk);

    private static TableColumn Col(string name, string type, bool nullable = true, string? def = null, int ord = 0, bool identity = false) =>
        new(name, type, nullable, def, ord, identity);

    [Theory]
    [InlineData("postgres", "\"id\"")]
    [InlineData("sqlite", "\"id\"")]
    [InlineData("mysql", "`id`")]
    [InlineData("sqlserver", "[id]")]
    public void QuoteId_follows_the_engine(string providerId, string expected) =>
        Assert.Equal(expected, CreateTableWriter.QuoteId(providerId, "id"));

    [Fact]
    public void QuoteId_escapes_the_delimiter()
    {
        Assert.Equal("[a]]b]", CreateTableWriter.QuoteId("sqlserver", "a]b"));
        Assert.Equal("`a``b`", CreateTableWriter.QuoteId("mysql", "a`b"));
        Assert.Equal("\"a\"\"b\"", CreateTableWriter.QuoteId("postgres", "a\"b"));
    }

    [Fact]
    public void Unqualified_when_schema_is_empty()
    {
        var t = Table("", "t", [Col("a", "int")]);
        Assert.Equal("\"t\"", CreateTableWriter.QuoteTable("postgres", t));
    }

    [Fact]
    public void Renders_columns_nullability_default_and_named_primary_key()
    {
        var t = Table("public", "person",
        [
            Col("id", "integer", nullable: false, ord: 1),
            Col("name", "character varying(100)", nullable: false, ord: 2),
            Col("note", "text", nullable: true, ord: 3),
            Col("active", "boolean", nullable: false, def: "true", ord: 4)
        ],
            new TablePrimaryKey("person_pkey", ["id"]));

        var sql = CreateTableWriter.Build("postgres", t, keepIdentity: true);

        Assert.Contains("CREATE TABLE \"public\".\"person\" (", sql);
        Assert.Contains("\"id\" integer NOT NULL", sql);
        Assert.Contains("\"name\" character varying(100) NOT NULL", sql);
        Assert.Contains("\"note\" text", sql);
        Assert.DoesNotContain("\"note\" text NOT NULL", sql);
        Assert.Contains("\"active\" boolean NOT NULL DEFAULT true", sql);
        Assert.Contains("CONSTRAINT \"person_pkey\" PRIMARY KEY (\"id\")", sql);
        Assert.EndsWith(");", sql);
    }

    [Fact]
    public void Unnamed_primary_key_when_constraint_name_is_null()
    {
        var t = Table("public", "t", [Col("a", "int", nullable: false, ord: 1)], new TablePrimaryKey(null, ["a"]));
        var sql = CreateTableWriter.Build("postgres", t, keepIdentity: true);
        Assert.Contains("PRIMARY KEY (\"a\")", sql);
        Assert.DoesNotContain("CONSTRAINT", sql);
    }

    [Fact]
    public void Columns_render_in_ordinal_order()
    {
        var t = Table("s", "t",
        [
            Col("c", "int", ord: 3),
            Col("a", "int", ord: 1),
            Col("b", "int", ord: 2)
        ]);
        var sql = CreateTableWriter.Build("mysql", t, keepIdentity: true);
        Assert.True(sql.IndexOf("`a`", StringComparison.Ordinal) < sql.IndexOf("`b`", StringComparison.Ordinal));
        Assert.True(sql.IndexOf("`b`", StringComparison.Ordinal) < sql.IndexOf("`c`", StringComparison.Ordinal));
    }

    [Fact]
    public void Keep_identity_renders_a_plain_column_and_drops_the_sequence_default()
    {
        // A Postgres serial reads as integer with a nextval default; keeping the values means a plain column so
        // the original ids insert cleanly, with the sequence default dropped.
        var t = Table("public", "t",
        [
            Col("id", "integer", nullable: false, def: "nextval('t_id_seq'::regclass)", ord: 1, identity: true),
            Col("name", "text", ord: 2)
        ]);

        var sql = CreateTableWriter.Build("postgres", t, keepIdentity: true);

        Assert.Contains("\"id\" integer NOT NULL", sql);
        Assert.DoesNotContain("nextval", sql);
        Assert.DoesNotContain("IDENTITY", sql);
        Assert.DoesNotContain("GENERATED", sql);
    }

    [Theory]
    [InlineData("postgres", "GENERATED BY DEFAULT AS IDENTITY")]
    [InlineData("sqlserver", "IDENTITY(1,1)")]
    [InlineData("mysql", "AUTO_INCREMENT")]
    public void Regenerate_identity_adds_the_engine_clause(string providerId, string clause)
    {
        var t = Table("dbo", "t",
        [
            Col("id", "int", nullable: false, def: "nextval('x')", ord: 1, identity: true),
            Col("name", "varchar(50)", ord: 2)
        ]);

        var sql = CreateTableWriter.Build(providerId, t, keepIdentity: false);

        Assert.Contains(clause, sql);
        // The sequence default is never emitted for an identity column, either way.
        Assert.DoesNotContain("nextval", sql);
    }

    [Fact]
    public void ColumnsForInsert_keeps_all_when_keeping_identity_and_drops_it_otherwise()
    {
        var t = Table("s", "t",
        [
            Col("id", "int", nullable: false, ord: 1, identity: true),
            Col("name", "text", ord: 2)
        ]);

        Assert.Equal(["id", "name"], CreateTableWriter.ColumnsForInsert(t, keepIdentity: true).Select(c => c.Name));
        Assert.Equal(["name"], CreateTableWriter.ColumnsForInsert(t, keepIdentity: false).Select(c => c.Name));
    }

    [Theory]
    [InlineData("postgres", "DROP TABLE IF EXISTS \"public\".\"t\";")]
    [InlineData("sqlserver", "DROP TABLE IF EXISTS [public].[t];")]
    [InlineData("mysql", "DROP TABLE IF EXISTS `public`.`t`;")]
    public void DropIfExists_quotes_for_the_engine(string providerId, string expected)
    {
        var t = Table("public", "t", [Col("a", "int")]);
        Assert.Equal(expected, CreateTableWriter.DropIfExists(providerId, t));
    }

    [Fact]
    public void Table_without_a_primary_key_has_no_primary_key_clause()
    {
        var t = Table("s", "t", [Col("a", "int", ord: 1)]);
        var sql = CreateTableWriter.Build("postgres", t, keepIdentity: true);
        Assert.DoesNotContain("PRIMARY KEY", sql);
    }
}
