// <auto-generated>
//     Generated by tools/generate-icons.py from the vendored Lucide SVGs in tools/lucide/.
//     Do NOT edit by hand — add or remove an SVG under tools/lucide/ and re-run the generator.
//     Lucide (https://lucide.dev) is licensed ISC; see THIRD-PARTY-NOTICES.md.
// </auto-generated>

using Avalonia.Media;

namespace SqlExplorer.App.ViewModels;

/// <summary>
/// Line-icon geometries flattened from Lucide SVGs, drawn as stroked Paths — the same idiom as
/// the hand-drawn <see cref="NodeIcons"/>. NodeIcons maps app concepts (a schema-tree node kind,
/// a toolbar action) onto these raw icons; render with a themed Stroke brush, Stretch="Uniform".
/// </summary>
public static class Icons
{
    /// <summary>Lucide <c>bot</c>.</summary>
    public static readonly Geometry Bot = Parse("M12 8V4H8 M 6 8 h 12 a 2 2 0 0 1 2 2 v 8 a 2 2 0 0 1 -2 2 h -12 a 2 2 0 0 1 -2 -2 v -8 a 2 2 0 0 1 2 -2 Z M2 14h2 M20 14h2 M15 13v2 M9 13v2");

    /// <summary>Lucide <c>box</c>.</summary>
    public static readonly Geometry Box = Parse("M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z M3.3 7 l 8.7 5 8.7 -5 M12 22V12");

    /// <summary>Lucide <c>check</c>.</summary>
    public static readonly Geometry Check = Parse("M20 6 9 17l-5-5");

    /// <summary>Lucide <c>chevron-down</c>.</summary>
    public static readonly Geometry ChevronDown = Parse("M6 9 l 6 6 6 -6");

    /// <summary>Lucide <c>chevron-right</c>.</summary>
    public static readonly Geometry ChevronRight = Parse("M9 18 l 6 -6 -6 -6");

    /// <summary>Lucide <c>circle-check</c>.</summary>
    public static readonly Geometry CircleCheck = Parse("M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0 Z M9 12 l 2 2 4 -4");

    /// <summary>Lucide <c>clock</c>.</summary>
    public static readonly Geometry Clock = Parse("M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0 Z M12 6v6l4 2");

    /// <summary>Lucide <c>copy</c>.</summary>
    public static readonly Geometry Copy = Parse("M 10 8 h 10 a 2 2 0 0 1 2 2 v 10 a 2 2 0 0 1 -2 2 h -10 a 2 2 0 0 1 -2 -2 v -10 a 2 2 0 0 1 2 -2 Z M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2");

    /// <summary>Lucide <c>database</c>.</summary>
    public static readonly Geometry Database = Parse("M 3 5 a 9 3 0 1 0 18 0 a 9 3 0 1 0 -18 0 Z M3 5V19A9 3 0 0 0 21 19V5 M3 12A9 3 0 0 0 21 12");

    /// <summary>Lucide <c>diamond</c>.</summary>
    public static readonly Geometry Diamond = Parse("M2.7 10.3a2.41 2.41 0 0 0 0 3.41l7.59 7.59a2.41 2.41 0 0 0 3.41 0l7.59-7.59a2.41 2.41 0 0 0 0-3.41l-7.59-7.59a2.41 2.41 0 0 0-3.41 0Z");

    /// <summary>Lucide <c>download</c>.</summary>
    public static readonly Geometry Download = Parse("M12 15V3 M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4 M7 10 l 5 5 5 -5");

    /// <summary>Lucide <c>eye</c>.</summary>
    public static readonly Geometry Eye = Parse("M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0 M 9 12 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0 Z");

    /// <summary>Lucide <c>file-code</c>.</summary>
    public static readonly Geometry FileCode = Parse("M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z M14 2v5a1 1 0 0 0 1 1h5 M10 12.5 8 15l2 2.5 M14 12.5 l 2 2.5 -2 2.5");

    /// <summary>Lucide <c>file-text</c>.</summary>
    public static readonly Geometry FileText = Parse("M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z M14 2v5a1 1 0 0 0 1 1h5 M10 9H8 M16 13H8 M16 17H8");

    /// <summary>Lucide <c>folder</c>.</summary>
    public static readonly Geometry Folder = Parse("M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z");

    /// <summary>Lucide <c>folder-open</c>.</summary>
    public static readonly Geometry FolderOpen = Parse("M6 14 l 1.5 -2.9 A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2");

    /// <summary>Lucide <c>folder-plus</c>.</summary>
    public static readonly Geometry FolderPlus = Parse("M12 10v6 M9 13h6 M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z");

    /// <summary>Lucide <c>key</c>.</summary>
    public static readonly Geometry Key = Parse("M15.5 7.5 l 2.3 2.3 a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4 M21 2 l -9.6 9.6 M 2 15.5 a 5.5 5.5 0 1 0 11 0 a 5.5 5.5 0 1 0 -11 0 Z");

    /// <summary>Lucide <c>keyboard</c>.</summary>
    public static readonly Geometry Keyboard = Parse("M10 8h.01 M12 12h.01 M14 8h.01 M16 12h.01 M18 8h.01 M6 8h.01 M7 16h10 M8 12h.01 M 4 4 h 16 a 2 2 0 0 1 2 2 v 12 a 2 2 0 0 1 -2 2 h -16 a 2 2 0 0 1 -2 -2 v -12 a 2 2 0 0 1 2 -2 Z");

    /// <summary>Lucide <c>list</c>.</summary>
    public static readonly Geometry List = Parse("M3 5h.01 M3 12h.01 M3 19h.01 M8 5h13 M8 12h13 M8 19h13");

    /// <summary>Lucide <c>list-ordered</c>.</summary>
    public static readonly Geometry ListOrdered = Parse("M11 5h10 M11 12h10 M11 19h10 M4 4h1v5 M4 9h2 M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02");

    /// <summary>Lucide <c>lock</c>.</summary>
    public static readonly Geometry Lock = Parse("M 5 11 h 14 a 2 2 0 0 1 2 2 v 7 a 2 2 0 0 1 -2 2 h -14 a 2 2 0 0 1 -2 -2 v -7 a 2 2 0 0 1 2 -2 Z M7 11V7a5 5 0 0 1 10 0v4");

    /// <summary>Lucide <c>palette</c>.</summary>
    public static readonly Geometry Palette = Parse("M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z M 13 6.5 a 0.5 0.5 0 1 0 1 0 a 0.5 0.5 0 1 0 -1 0 Z M 17 10.5 a 0.5 0.5 0 1 0 1 0 a 0.5 0.5 0 1 0 -1 0 Z M 6 12.5 a 0.5 0.5 0 1 0 1 0 a 0.5 0.5 0 1 0 -1 0 Z M 8 7.5 a 0.5 0.5 0 1 0 1 0 a 0.5 0.5 0 1 0 -1 0 Z");

    /// <summary>Lucide <c>pencil</c>.</summary>
    public static readonly Geometry Pencil = Parse("M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z M15 5 l 4 4");

    /// <summary>Lucide <c>play</c>.</summary>
    public static readonly Geometry Play = Parse("M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z");

    /// <summary>Lucide <c>plus</c>.</summary>
    public static readonly Geometry Plus = Parse("M5 12h14 M12 5v14");

    /// <summary>Lucide <c>puzzle</c>.</summary>
    public static readonly Geometry Puzzle = Parse("M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z");

    /// <summary>Lucide <c>rectangle-vertical</c>.</summary>
    public static readonly Geometry RectangleVertical = Parse("M 8 2 h 8 a 2 2 0 0 1 2 2 v 16 a 2 2 0 0 1 -2 2 h -8 a 2 2 0 0 1 -2 -2 v -16 a 2 2 0 0 1 2 -2 Z");

    /// <summary>Lucide <c>refresh-cw</c>.</summary>
    public static readonly Geometry RefreshCw = Parse("M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8 M21 3v5h-5 M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16 M8 16H3v5");

    /// <summary>Lucide <c>search</c>.</summary>
    public static readonly Geometry Search = Parse("M21 21 l -4.34 -4.34 M 3 11 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0 Z");

    /// <summary>Lucide <c>server</c>.</summary>
    public static readonly Geometry Server = Parse("M 4 2 h 16 a 2 2 0 0 1 2 2 v 4 a 2 2 0 0 1 -2 2 h -16 a 2 2 0 0 1 -2 -2 v -4 a 2 2 0 0 1 2 -2 Z M 4 14 h 16 a 2 2 0 0 1 2 2 v 4 a 2 2 0 0 1 -2 2 h -16 a 2 2 0 0 1 -2 -2 v -4 a 2 2 0 0 1 2 -2 Z M 6 6 L 6.01 6 M 6 18 L 6.01 18");

    /// <summary>Lucide <c>sliders-horizontal</c>.</summary>
    public static readonly Geometry SlidersHorizontal = Parse("M10 5H3 M12 19H3 M14 3v4 M16 17v4 M21 12h-9 M21 19h-5 M21 5h-7 M8 10v4 M8 12H3");

    /// <summary>Lucide <c>square-function</c>.</summary>
    public static readonly Geometry SquareFunction = Parse("M 5 3 h 14 a 2 2 0 0 1 2 2 v 14 a 2 2 0 0 1 -2 2 h -14 a 2 2 0 0 1 -2 -2 v -14 a 2 2 0 0 1 2 -2 Z M9 17c2 0 2.8-1 2.8-2.8V10c0-2 1-3.3 3.2-3 M9 11.2h5.7");

    /// <summary>Lucide <c>square-terminal</c>.</summary>
    public static readonly Geometry SquareTerminal = Parse("M7 11 l 2 -2 -2 -2 M11 13h4 M 5 3 h 14 a 2 2 0 0 1 2 2 v 14 a 2 2 0 0 1 -2 2 h -14 a 2 2 0 0 1 -2 -2 v -14 a 2 2 0 0 1 2 -2 Z");

    /// <summary>Lucide <c>table</c>.</summary>
    public static readonly Geometry Table = Parse("M12 3v18 M 5 3 h 14 a 2 2 0 0 1 2 2 v 14 a 2 2 0 0 1 -2 2 h -14 a 2 2 0 0 1 -2 -2 v -14 a 2 2 0 0 1 2 -2 Z M3 9h18 M3 15h18");

    /// <summary>Lucide <c>terminal</c>.</summary>
    public static readonly Geometry Terminal = Parse("M12 19h8 M4 17 l 6 -6 -6 -6");

    /// <summary>Lucide <c>trash-2</c>.</summary>
    public static readonly Geometry Trash2 = Parse("M10 11v6 M14 11v6 M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6 M3 6h18 M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2");

    /// <summary>Lucide <c>trending-up</c>.</summary>
    public static readonly Geometry TrendingUp = Parse("M16 7h6v6 M22 7 l -8.5 8.5 -5 -5 L2 17");

    /// <summary>Lucide <c>triangle-alert</c>.</summary>
    public static readonly Geometry TriangleAlert = Parse("M21.73 18 l -8 -14 a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3 M12 9v4 M12 17h.01");

    /// <summary>Lucide <c>upload</c>.</summary>
    public static readonly Geometry Upload = Parse("M12 3v12 M17 8 l -5 -5 -5 5 M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4");

    /// <summary>Lucide <c>user</c>.</summary>
    public static readonly Geometry User = Parse("M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2 M 8 7 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0 Z");

    /// <summary>Lucide <c>users</c>.</summary>
    public static readonly Geometry Users = Parse("M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M16 3.128a4 4 0 0 1 0 7.744 M22 21v-2a4 4 0 0 0-3-3.87 M 5 7 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0 Z");

    /// <summary>Lucide <c>x</c>.</summary>
    public static readonly Geometry X = Parse("M18 6 6 18 M6 6 l 12 12");

    /// <summary>Lucide <c>zap</c>.</summary>
    public static readonly Geometry Zap = Parse("M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z");

    private static Geometry Parse(string data) => StreamGeometry.Parse(data);
}
